version: '3.8'

services:
  app:
    image: bms-application
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/book_my_show
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_DATABASE_PORT: 3306
    depends_on:
      - db
    networks:
      - bms_app


  db:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      DATABASE_HOST: bms-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: book_my_show
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - 3307:3306
    networks:
      - bms_app
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    depends_on:
      - db
    networks:
      - bms_app


networks:
    bms_app: